var node_url_lib=(function(){function m(a){switch(typeof a){case "string":return a;case "boolean":return a?"true":"false";case "number":return isFinite(a)?a:"";default:return""}}function x(a,b,c){a/=c?D:2;a+=~~(a/b);for(var b=l-o,c=~~(b*p/2),d=0;a>c;d+=l)a=~~(a/b);return d+~~((l-o+1)*a/(a+E))}function F(a,b){for(var c=1114112,d=0,e=a.length;d<e;++d){var f=a[d];f>=b&&f<c&&(c=f)}if(c>=1114112)throw Error("Next smallest code point not found.");return c}function G(a){if(a>=48&&a<=57)return a-22;if(a>=65&&a<=90)return a-
65;if(a>=97&&a<=122)return a-97;throw Error("Illegal digit #"+a);}function H(a,b){for(var c=[],d=l,e=b;;d+=l){var f=d<=a+o?o:d>=a+p?p:d-a;if(e<f){c.push(e+(e<26?97:22));break}else c.push(f+(e-f)%(l-f)+(f+(e-f)%(l-f)<26?97:22)),e=~~((e-f)/(l-f))}return c}function i(a){return a.charCodeAt(0)}function r(a,b,c){if(a&&typeof a==="object"&&a.href)return a;if(typeof a!=="string")throw new TypeError("Parameter 'url' must be a string, not "+typeof a);for(var d={},e=0,f=a.length;e<f;e++)if(n.indexOf(a.charAt(e))===
-1)break;e!==0&&(a=a.substr(e));var h=I.exec(a);if(h){var h=h[0],j=h.toLowerCase();d.protocol=j;a=a.substr(h.length)}if(c||h||a.match(/^\/\/[^@\/]+@[^@\/]+/)){var g=a.substr(0,2)==="//";if(g&&(!h||!u[h]))a=a.substr(2),d.d=!0}if(!u[h]&&(g||h&&!q[h])){g=a.indexOf("@");if(g!==-1){for(var i=!0,e=0,f=s.length;e<f;e++)if(c=a.indexOf(s[e]),c!==-1&&c<g){i=!1;break}if(i)d.b=a.substr(0,g),a=a.substr(g+1)}g=-1;e=0;for(f=y.length;e<f;e++)if(c=a.indexOf(y[e]),c!==-1&&(g<0||c<g))g=c;g!==-1?(d.host=a.substr(0,g),
a=a.substr(g)):(d.host=a,a="");e=d.host;c={};if(f=J.exec(e))f=f[0],c.port=f.substr(1),e=e.substr(0,e.length-f.length);if(e)c.hostname=e;if(d.b)d.host=d.b+"@"+d.host;g=Object.keys(c);e=0;for(f=g.length;e<f;e++)i=g[e],d[i]=c[i];d.hostname=d.hostname||"";if(d.hostname.length>K)d.hostname="";else{g=d.hostname.split(/\./);e=0;for(f=g.length;e<f;e++)if((c=g[e])&&!c.match(z)){for(var i="",k=0,l=c.length;k<l;k++)i+=c.charCodeAt(k)>127?"x":c[k];if(!i.match(z)){f=g.slice(0,e);e=g.slice(e+1);if(c=c.match(L))f.push(c[1]),
e.unshift(c[2]);e.length&&(a="/"+e.join(".")+a);d.hostname=f.join(".");break}}}d.hostname=d.hostname.toLowerCase();f=d.hostname.split(".");c=[];for(e=0;e<f.length;++e)g=f[e],c.push(g.match(/[^A-Za-z0-9_-]/)?"xn--"+M.c(g):g);d.hostname=c.join(".");d.host=(d.b?d.b+"@":"")+(d.hostname||"")+(d.port?":"+d.port:"");d.href+=d.host}if(!N[j]){e=0;for(f=v.length;e<f;e++)j=v[e],c=encodeURIComponent(j),c===j&&(c=escape(j)),a=a.split(j).join(c);j=a.length;e=0;for(f=n.length;e<f;e++)c=a.indexOf(n[e]),c!==-1&&(j=
Math.min(c,j));a=a.substr(0,j)}j=a.indexOf("#");if(j!==-1)d.hash=a.substr(j),a=a.slice(0,j);j=a.indexOf("?");if(j!==-1){d.search=a.substr(j);d.a=a.substr(j+1);if(b)d.a=A.parse(d.a);a=a.slice(0,j)}else if(b)d.search="",d.a={};if(a)d.pathname=a;if(q[h]&&d.hostname&&!d.pathname)d.pathname="/";d.href=t(d);return d}function t(a){typeof a==="string"&&(a=r(a));var b=a.b;if(b)for(var b=b.split("@").join("%40"),c=0,d=s.length;c<d;c++)var e=s[c],b=b.split(e).join(encodeURIComponent(e));var c=a.protocol||"",
b=a.host!==void 0?a.host:a.hostname!==void 0?(b?b+"@":"")+a.hostname+(a.port?":"+a.port:""):!1,d=a.pathname||"",e=a.a&&(typeof a.a==="object"&&Object.keys(a.a).length?A.stringify(a.a):"")||"",e=a.search||e&&"?"+e||"",f=a.hash||"";c&&c.substr(-1)!==":"&&(c+=":");a.d||(!c||q[c])&&b!==!1?(b="//"+(b||""),d&&d.charAt(0)!=="/"&&(d="/"+d)):b||(b="");f&&f.charAt(0)!=="#"&&(f="#"+f);e&&e.charAt(0)!=="?"&&(e="?"+e);return c+b+d+e+f}function O(a,b){if(!a)return b;a=r(t(a),!1,!0);b=r(t(b),!1,!0);a.hash=b.hash;
if(b.href==="")return a;if(b.d&&!b.protocol)return b.protocol=a.protocol,b;if(b.protocol&&b.protocol!==a.protocol){if(!q[b.protocol])return b;a.protocol=b.protocol;if(!b.host&&!u[b.protocol]){for(var c=(b.pathname||"").split("/");c.length&&!(b.host=c.shift()););if(!b.host)b.host="";c[0]!==""&&c.unshift("");c.length<2&&c.unshift("");b.pathname=c.join("/")}a.pathname=b.pathname;a.search=b.search;a.a=b.a;a.host=b.host||"";delete a.b;delete a.hostname;a.port=b.port;return a}var d=a.pathname&&a.pathname.charAt(0)===
"/",e=b.host!==void 0||b.pathname&&b.pathname.charAt(0)==="/",f=d=e||d||a.host&&b.pathname,h=a.pathname&&a.pathname.split("/")||[],c=b.pathname&&b.pathname.split("/")||[],j=a.protocol&&!q[a.protocol]&&a.host!==void 0;if(j){delete a.hostname;delete a.b;delete a.port;if(a.host)h[0]===""?h[0]=a.host:h.unshift(a.host);delete a.host;if(b.protocol){delete b.hostname;delete b.b;delete b.port;if(b.host)c[0]===""?c[0]=b.host:c.unshift(b.host);delete b.host}d=d&&(c[0]===""||h[0]==="")}if(e)a.host=b.host||b.host===
""?b.host:a.host,a.search=b.search,a.a=b.a,h=c;else if(c.length)h||(h=[]),h.pop(),h=h.concat(c),a.search=b.search,a.a=b.a;else if("search"in b){if(j)a.host=h.shift();a.search=b.search;a.a=b.a;return a}if(!h.length)return delete a.pathname,a;for(var e=h.slice(-1)[0],c=(a.host||b.host)&&(e==="."||e==="..")||e==="",g=0,i=h.length;i>=0;i--)e=h[i],e=="."?h.splice(i,1):e===".."?(h.splice(i,1),g++):g&&(h.splice(i,1),g--);if(!d&&!f)for(;g--;)h.unshift("..");d&&h[0]!==""&&(!h[0]||h[0].charAt(0)!=="/")&&h.unshift("");
c&&h.join("/").substr(-1)!=="/"&&h.push("");f=h[0]===""||h[0]&&h[0].charAt(0)==="/";if(j)a.host=f?"":h.shift();(d=d||a.host&&h.length)&&!f&&h.unshift("");a.pathname=h.join("/");return a}Object.keys||(Object.keys=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b});Array.isArray||(Array.isArray=function(a){return{}.toString.call(a)=="[object Array]"});var M={c:function(a){if(typeof a!="string")throw Error("Argument must be a string.");for(var a=a.split("").map(function(a){return a.charCodeAt(0)}),
b=[],c=[],d=0,e=a.length;d<e;++d){var f=a[d];f<128?b.push(f):c.push(f)}var h,i;(h=i=b.length)&&b.push(45);for(var g=B,k=C,l=0,e=a.length;i<e;++g,++l){d=F(c,g);l+=(d-g)*(i+1);g=d;for(d=0;d<e;++d)if(f=a[d],f<g){if(++l==P)throw Error("Delta overflow.");}else f==g&&(b=b.concat(H(k,l)),k=x(l,i+1,h==i),l=0,i++)}return String.fromCharCode.apply(String,b)},e:function(a){if(typeof a!="string")throw Error("Argument must be a string.");for(var b=1+a.lastIndexOf("-"),a=a.split("").map(function(a){return a.charCodeAt(0)}),
c=a.slice(0,b?b-1:0),d=B,e=C,f=0,h=a.length;b<h;++f){for(var i=f,g=l,k=1;;g+=l){var m=G(a[b++]);f+=m*k;var n=g<=e+o?o:g>=e+p?p:g-e;if(m<n)break;k*=l-n}g=1+c.length;e=x(f-i,g,i==0);d+=~~(f/g);f%=g;c.splice(f,0,d)}return String.fromCharCode.apply(String,c)}},o=1,p=26,l=36,E=38,D=700,B=128,C=72,P=Math.pow(2,53),k={f:function(a,b){for(var c=new Buffer(a.length),d="CHAR",e,f,h,j=0,g=0;j<=a.length;j++)switch(f=a.charCodeAt(j),d){case "CHAR":switch(f){case i("%"):e=0;d="HEX0";break;case i("+"):b&&(f=i(" "));
default:c[g++]=f}break;case "HEX0":d="HEX1";h=f;if(i("0")<=f&&f<=i("9"))e=f-i("0");else if(i("a")<=f&&f<=i("f"))e=f-i("a")+10;else if(i("A")<=f&&f<=i("F"))e=f-i("A")+10;else{c[g++]=i("%");c[g++]=f;d="CHAR";break}break;case "HEX1":d="CHAR";if(i("0")<=f&&f<=i("9"))f-=i("0");else if(i("a")<=f&&f<=i("f"))f=f-i("a")+10;else if(i("A")<=f&&f<=i("F"))f=f-i("A")+10;else{c[g++]=i("%");c[g++]=h;c[g++]=f;break}c[g++]=16*e+f}return c.slice(0,g-1)}};k.unescape=function(a,b){return k.f(a,b).toString()};k.escape=
function(a){return encodeURIComponent(a)};k.stringify=k.c=function(a,b,c,d){b=b||"&";c=c||"=";a=a===null?void 0:a;switch(typeof a){case "object":return Object.keys(a).map(function(e){return Array.isArray(a[e])?a[e].map(function(a){return k.escape(m(e))+c+k.escape(m(a))}).join(b):k.escape(m(e))+c+k.escape(m(a[e]))}).join(b);default:return!d?"":k.escape(m(d))+c+k.escape(m(a))}};k.parse=k.e=function(a,b,c){var c=c||"=",d={};if(typeof a!=="string"||a.length===0)return d;a.split(b||"&").forEach(function(a){var b=
a.split(c),a=k.unescape(b[0],!0),b=k.unescape(b.slice(1).join(c),!0);a in d?Array.isArray(d[a])?d[a].push(b):d[a]=[d[a],b]:d[a]=b});return d};var I=/^([a-z0-9]+:)/i,J=/:[0-9]+$/,n='<,>,",`, ,\r,\n,\t'.split(","),v=["'"],y=["%","/","?",";","#"].concat("{,},|,\\,^,~,[,],`".split(",").concat(n)).concat(v),s=["/","@","?","#"].concat(n),K=255,z=/^[a-zA-Z0-9][a-z0-9A-Z_-]{0,62}$/,L=/^([a-zA-Z0-9][a-z0-9A-Z_-]{0,62})(.*)$/,N={javascript:!0,"javascript:":!0},u={javascript:!0,"javascript:":!0},q={http:!0,
https:!0,ftp:!0,gopher:!0,file:!0,"http:":!0,"https:":!0,"ftp:":!0,"gopher:":!0,"file:":!0},A=k,w={};w.parse=r;w.resolve=function(a,b){return t(O(a,b))};return w})();